#1. login for user
###
POST http://localhost:5000/login
Content-Type: application/json

{
    "email": "ujangarifin06@gmail.com",
    "password" : "123456"
}

#2. Status for user
###
GET http://localhost:5000/status


#3. logout for user
###
DELETE http://localhost:5000/logout